### ISSUE TITLE
Testing for Failures

### ISSUE THREAD

**Issue by DeanPhillipsOKC** [vocksel/code-cop#2]
Nice plugin!  However, sometimes it is useful to write a test that we expect to fail (e.g., verify that certain inputs yield an error).  I tried to wrap the invocation of my uut in a pcall, and assert that it returns false, but it looks like the pcall in the plugins TestCase script still interprets the call as a failure.

I was going to modify my local plugin to allow the passing of a flag to indicate an expected failure, and to invert the built-in assertion following the pcall to the callback, but wanted to post an issue first, in case there is already a built-in and recommended way of doing this.

**Comment by DeanPhillipsOKC** [comment]
Nevermind.  I just realized that using a pcall and asserting it returns false works just fine for these needs.  My lack of Lua knowledge led to a small syntax error originally (accidentally put the result of the uut call in the pcall, rather than a function).  *Hangs head in shame*

**Comment by vocksel** [comment]
Hey! Just wanted to let you know about [TestEZ](https://github.com/Roblox/testez), which if you're willing to switch from Code Cop should provide you a lot more niceties and familiar syntax. It _is_ slated for a rework but haven't heard anything recently. Either way writing your tests for it should be safe, I think the biggest thing changing would be how you interface with it and kick off your tests.

For the most part, Code Cop tests can translate 1:1 given you're just writing `describe()` and `it()` blocks as a table.

**Comment by DeanPhillipsOKC** [comment]
Hello!  Solid recommendation.  I actually moved to TestEZ, Lemur, Rojo,
Rodux, and Roact about a week after I sent my original email.  I'm really
enjoying the workflow, as it's more in my wheelhouse (web app developer).

Thanks for reaching out, and have a great day Sir!
--Dean Phillips
